<?php
return array (
  'search' => 'Искать',
  'actions' => 'Действия',
  'settings' => 'Параметры',
  'notFound' => 'Ничего не найдено',
  'concept' => 'Понятие',
  'core' => 'Ядро',
  'utilities' => 'Коммунальные услуги',
  'components' => 'Компоненты',
  'smart components' => 'Умные компоненты',
  'russian' => 'Русский',
  'dark' => 'Темный',
  'off' => 'Выключен',
  'on' => 'Включен',
  'wide' => 'Широкий формат',
  'text size' => 'Размер текста',
  'reduced' => 'Уменьшенный',
  'default' => 'По умолчанию',
  'increased' => 'Повышенный',
  'edit article' => 'Редактировать статью',
  'report a bug' => 'Сообщить об ошибке',
  'previous' => 'Предыдущий',
  'next' => 'Следующий',
);
