<?php
    return [
        'search' => 'Поиск',
        'actions' => 'Действия',
        'settings' => 'Настройки',
        'notFound' => 'Ничего не найдено',
        'concept' => 'Концепция',
        'core' => 'Ядро',
        'utilities' => 'Утилиты',
        'components' => 'Компоненты',
        'smart components' => 'Смарт-компоненты',
        'russian' => 'Русский',
        'dark' => 'Темная',
        'off' => 'Выключено',
        'on' => 'Включено',
        'wide' => 'Широкий экран',
        'text size' => 'Размер текста',
        'reduced' => 'Меньше',
        'default' => 'Стандартный',
        'increased' => 'Больше',
    ];
